# Generated by Django 4.1.3 on 2022-11-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'gram'), ('tbsp', 'tablespoon'), ('tsp', 'teaspoon'), ('l', 'liter'), ('ea', 'each'), ('cup', 'cup'), ('oz', 'ounce'), ('lbs', 'pound'), ('', '')], default='', max_length=10, verbose_name='Unit of Measure'),
        ),
    ]
